name: Test insert BD

on:
  workflow_dispatch:

jobs:
  test-db:
    runs-on: ubuntu-latest

    steps:
      - name: Installer PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Insérer un message dans la BDD AlwaysData
        env:
          PGHOST: ${{ secrets.AD_DB_HOST }}
          PGPORT: ${{ secrets.AD_DB_PORT }}
          PGDATABASE: ${{ secrets.AD_DB_NAME }}
          PGUSER: ${{ secrets.AD_DB_USER }}
          PGPASSWORD: ${{ secrets.AD_DB_PASSWORD }}
        run: |
           echo "INSERT INTO article (title, link, category, date, source, created_at) VALUES ('Test GitHub Actions', 'https://example.com', 'test', CURRENT_TIMESTAMP, 'actions', CURRENT_TIMESTAMP);" > insert.sql
           psql -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" -f insert.sql
