name: Test insert BD

on:
  workflow_dispatch:

jobs:
  test-db:
    runs-on: ubuntu-latest

    steps:
      - name: Installer PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Insérer un message dans la BDD AlwaysData
        env:
          PGHOST: ${{ secrets.AD_PG_HOST }}
          PGPORT: ${{ secrets.AD_PG_PORT }}
          PGDATABASE: ${{ secrets.AD_PG_DB }}
          PGUSER: ${{ secrets.AD_PG_USER }}
          PGPASSWORD: ${{ secrets.AD_PG_PASSWORD }}
        run: |
          echo "INSERT INTO test (message) VALUES ('Depuis GitHub Actions via PostgreSQL');" > insert.sql
          psql --no-password -f insert.sql
